// exercises/react18_typescript_vite/src/components/MyCounter.tsx
import { useState } from 'react';

function MyCounter() {
  const [count, setCount] = useState(0);

  function handleClick() {
    setCount(count + 1);
  }

  return (
    <div>
      <button>Click me to increase counter:</button>
      <br />
      <br />
      <h2>Count: {count}</h2>
    </div>
  );
}

export default MyCounter;

// exercises/vue2_typescript/src/components/my-counter.vue
<template>
  <div>
    <v-btn> Click me to increase counter:</v-btn>
    <br />
    <br />
    <h2>Count:{{count}}</h2>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  data() {
    return {
      count: 0,
    };
  },
  methods: {
    clickBtn() {
      this.count += 1;
    },
  },
});
</script>
<style scoped>

</style>
