// exercises/react18_typescript_vite/src/views/Names.tsx
import ListOfNames from '../components/ListOfNames';

const names = ['Chris', 'Paul', 'Douglas', 'Jordan'];

function Names() {
  return (
    <div>
      <h1>Names</h1>
      <div style={{ padding: '20px', border: '1px solid #ccc', borderRadius: '8px' }}>
        <ListOfNames names={names} />
      </div>
    </div>
  );
}

export default Names;

// exercises/vue2_typescript/src/views/Names.vue
<template>
  <v-container>
    <h1>Names</h1>
    <v-card>
      <v-card-text>

      </v-card-text>
    </v-card>
  </v-container>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  data() {
    return {
      names: ['Chris', 'Paul', 'Douglas', 'Jordan'],
    };
  },
  components: {

  },
});

</script>
